spring:
  application:
    name: e_commerce_api
  datasource:
    url:  jdbc:mysql://localhost:3306/e_commerce_db?createDatabaseIfNotExist=true
    username: root
    password: Pass@747word
  jpa:
    show-sql: true
  jwt:
    secret: ${JWT_SECRET}
    accessTokenExpiration: 604800
    refreshTokenExpiration: 604800
  mail:
    host: smtp.gmail.com
    port: 587
    username: abrahamowino129@gmail.com
    password: ${GMAIL_APP_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
